version: "3.9"
services:
  mongo:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=mastro
  catalogue:
    build: 
      context: .
      dockerfile: catalogue/Dockerfile
    ports:
      - 8085:8085
    volumes:
      - ./compose-confs/mongo-catalogue.yml:/conf/mongo-catalogue.yml
    environment:
      - MASTRO_CONFIG=/conf/mongo-catalogue.yml
    depends_on:
      - mongo
  featurestore:
    build: 
      context: .
      dockerfile: featurestore/Dockerfile
    ports:
      - 8086:8085
    volumes:
      - ./compose-confs/mongo-fs.yml:/conf/mongo-fs.yml
    environment:
      - MASTRO_CONFIG=/conf/mongo-fs.yml
    depends_on:
      - mongo
  metricstore:
    build: 
      context: .
      dockerfile: metricstore/Dockerfile
    ports:
      - 8087:8085
    volumes:
      - ./compose-confs/mongo-ms.yml:/conf/mongo-ms.yml
    environment:
      - MASTRO_CONFIG=/conf/mongo-ms.yml
    depends_on:
      - mongo
  embeddingstore:
    build: 
      context: .
      dockerfile: embeddingstore/Dockerfile
    ports:
      - 8089:8085
    volumes:
      - ./compose-confs/milvus-es.yml:/conf/milvus-es.yml
    environment:
      - MASTRO_CONFIG=/conf/milvus-es.yml
    depends_on:
      - mongo
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 8088:80
    environment:
      - NGINX_PORT=80
      - CATALOGUE_URL="http://catalogue:8085/"
      - FEATURESTORE_URL="http://featurestore:8085/"
      - METRICSTORE_URL="http://metricstore:8085/"
    depends_on:
      - mongo
      - catalogue
      - featurestore

volumes:
  mongo-data:
  mongo-config: