ARG nginx_version=1.19.8-alpine
FROM nginx:${nginx_version}

EXPOSE 8080

#COPY . /code
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf