name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    #- name: Install krb5 and gosasl
    #  run: |
    #    sudo apt-get install libkrb5-dev
    #    go get -tags=kerberos github.com/beltran/gosasl
    #    go get -tags=kerberos github.com/beltran/gohive

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Build the Docker image
      run: |
        #TAG=$(date +%Y%m%d)
        TAG=$GIT_TAG_NAME
        # statically built ones use CGO_ENABLED=0 ---
        # mvc
        docker build mvc --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/mvc:${TAG}
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mvc:${TAG}
        # catalogue
        docker build catalogue --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-catalogue:${TAG}
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-catalogue:${TAG}
        # featurestore
        docker build featurestore --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-featurestore:${TAG}
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-featurestore:${TAG}
        # dynamically built ones use CGO_ENABLED=1 ---
        # crawlers

        # mastro ui
        docker build ui --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-ui:${TAG}
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mastro-ui:${TAG}
        