name: Docker Build Crawlers

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: set env
      run: |
        TAG=${GIT_TAG_NAME:-$(date +%Y%m%d)}
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo "IMAGE=mastro-crawlers" >> $GITHUB_ENV

    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    # - name: Set up Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.15

    #- name: Install krb5 and gosasl
    #  run: |
    #    sudo apt-get install libkrb5-dev
    #    go get -tags=kerberos github.com/beltran/gosasl
    #    go get -tags=kerberos github.com/beltran/gohive

    - name: Build the Docker image
      run: |
        docker build -f crawlers/Dockerfile . --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.TAG }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.TAG }}'
        format: 'table'
        #exit-code: '1'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.TAG }}