name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Build the Docker image
      run: |
        docker build mvc --tag ${{ secrets.DOCKERHUB_ORGANIZATION }}/mvc:${GIT_TAG_NAME}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/${{ secrets.DOCKERHUB_ORGANIZATION }}/mvc:${GIT_TAG_NAME}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Build the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mvc:${GIT_TAG_NAME}